"""add user tariff fields

Revision ID: 87928d36d9f0
Revises: 
Create Date: 2025-10-11 18:34:06.781420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87928d36d9f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tariff', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('autopay', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('expire_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'Tariff', ['tariff'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'expire_date')
    op.drop_column('users', 'autopay')
    op.drop_column('users', 'name')
    op.drop_column('users', 'tariff')
    # ### end Alembic commands ###
